### ISSUE TITLE
SQL QUERY

### ISSUE THREAD

**Issue by ghost** [ravi-sharma/wallet#1]
Can you give the example sql query?

**Comment by ravi-sharma** [comment]
@ahmadnurus Please see: https://laravel.com/docs/5.5/queries for the same. Good to see you here
 :)

**Comment by ghost** [comment]
Oke, Thanks :D

**Comment by ghost** [comment]
but I mean, query the database structure for your project, like tables and columns

**Comment by ravi-sharma** [comment]
Please see: https://github.com/ravi-sharma/wallet/blob/master/wallet.sql
